# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_address_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientaddress',
            name='client',
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('1', 'facturation'), ('2', 'livraison')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClientAddress',
        ),
    ]
