# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(choices=[(0.055, '5.5%'), (0.1, '10%'), (0.2, '20%')]),
        ),
    ]
