# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160523_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='designation',
        ),
    ]
