# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20160518_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='payement_date',
            new_name='paiement_date',
        ),
    ]
